version: "3.7"
services:
    app:
        environment:
            - APP_DEBUG_MODE=True
            - APP_TEST_MODE=False
        container_name: ws_portal
        image: ws_portal:dev
        build:
            context: ./resources
            args:
            - IMAGE_DESCRIPTION=WS Portal, development image
        ports:
            - 8000:80
        volumes:
            - ./app:/var/www/html
            - ./logs:/var/www/log
            - ./modulos:/var/www/html/modulos
            - ./intranet:/var/www/html/intranet
            - ./resources/entrypoint.sh:/tmp/entrypoint.sh:ro
            - ./resources/hosts:/etc/hosts
            - ./resources/php.ini:/etc/php5/cli/php.ini
            - ./resources/php.ini:/etc/php5/apache2/php.ini
            - ./resources/config_local.php:/var/www/html/lib/config_local.php
            - ./resources/intranet/config_local.php:/var/www/html/intranet/lib/config_local.php
            - ./resources/intranet/init.php:/var/www/html/intranet/lib/init.php
#        healthcheck:
#            test: curl -f http://localhost || exit 1
#            interval: 10s
#            retries: 3
#            start_period: 30s